services:
    ongr_magento.sql_relations.category.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [catalog_category_entity, D, OLD.entity_id, 1, category]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_magento.sql_relations.category.join.products ] ]

    ongr_magento.sql_relations.category.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [catalog_category_entity, U, OLD.entity_id, 1, category]
        tags:
            - { name: ongr_connections.extraction_descriptor }
        calls:
            - [ addRelation, [ @ongr_magento.sql_relations.category.join.products ] ]

    ongr_magento.sql_relations.category.join.products:
        class: %ongr_connections.extractor.join_relation.class%
        arguments: [catalog_category_product AS ccp, ccp.product_id, ccp.category_id=NEW.entity_id, product, U, 1]

    ongr_magento.sql_relations.product.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [catalog_product_entity, C, NEW.entity_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_magento.sql_relations.product.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [catalog_product_entity, U, OLD.entity_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_magento.sql_relations.product.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [catalog_product_entity, D, OLD.entity_id, 1, product]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_magento.sql_relations.content.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [cms_page, D, OLD.page_id, 1, content]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_magento.sql_relations.content.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [cms_page, U, OLD.page_id, 1, content]
        tags:
            - { name: ongr_connections.extraction_descriptor }

    ongr_magento.sql_relations.content.create:
            class: %ongr_connections.extractor.descriptor.class%
            arguments: [cms_page, C, NEW.page_id, 1, content]
            tags:
                - { name: ongr_connections.extraction_descriptor }
