parameters:
    ongr_magento.triggers.categories.track_fields:
        - entity_id
        - created_at
        - updated_at

services:
    # Products triggers
    ongr_magento.triggers.categories_insert:
        class: %ongr_magento.triggers.simple_trigger.class%
        arguments: [catalog_category_entity, C, 1, category, NEW.entity_id]
        tags:
            - { name: ongr_connections.trigger, trigger: categories_insert }

    ongr_magento.triggers.categories_update:
        class: %ongr_magento.triggers.simple_trigger.class%
        arguments: [catalog_category_entity, U, 1, category, NEW.entity_id, %ongr_magento.triggers.categories.track_fields%]
        tags:
            - { name: ongr_connections.trigger, trigger: categories_update }

    ongr_magento.triggers.categories_delete:
        class: %ongr_magento.triggers.simple_trigger.class%
        arguments: [catalog_category_entity, D, 1, category, OLD.entity_id]
        tags:
            - { name: ongr_connections.trigger, trigger: categories_delete }
